### ISSUE TITLE
IConnectionParams port and host type and naming convention

### ISSUE THREAD

**Issue by lenkan** [buildondata/deno-postgres#113]
IConnectionParams should be modelled like:

```
interface IConnectionParams {
    hostname?: string
    port?: number
}
```

Rather than the current

```
interface IConnectionParams {
    host?: string
    port?: string
}
```

I understand this is probably inherited  from `node-postgres` but there is also an opportunity to align simple things like this in Deno user land from the start. I believe this aligns better with the convention currently set by `Deno.listen` API. In addition, this is what is used in https://github.com/keroxp/deno-redis . I've also used it for https://github.com/lenkan/deno-amqp.

If you agree, I can submit a PR with the changes. If you don't agree, feel free to close this issue.

**Comment by bartlomieju** [comment]
Yeah, I'm fine with that change 👍
