### ISSUE TITLE
'name' column type parsing method is not implemented

### ISSUE THREAD

**Issue by rokoucha** [buildondata/deno-postgres#76]
I got uncaught error when execute query
```
error: Uncaught Error: Don't know how to parse column type: 19
► decode.ts:212:13

212       throw new Error(`Don't know how to parse column type: ${typeOid}`);
                ^

    at decodeText (decode.ts:212:13)
    at decode (decode.ts:220:12)
    at _parseDataRow (query.ts:35:24)
    at handleDataRow (query.ts:47:28)
    at _preparedQuery (connection.ts:505:18)
```
and the query is
```
SELECT * FROM information_schema.tables
```

According to documents, PostgreSQL has 'name' special character types and that type is internal type for object names.
https://www.postgresql.org/docs/current/datatype-character.html#DATATYPE-CHARACTER-SPECIAL-TABLE

However in deno-postgres, 'name' column type is impleted in here
https://github.com/buildondata/deno-postgres/blob/7a27fd94c7b765ca256b3da96a9de94f380e6bbe/oid.ts#L5

but parsing method is not implemented.
https://github.com/buildondata/deno-postgres/blob/7a27fd94c7b765ca256b3da96a9de94f380e6bbe/decode.ts#L182-L213

----------------

deno-postgres v0.3.4
deno 0.26.0
postgres 12.1

**Comment by bartlomieju** [comment]
@rokoucha thanks for opening the issue. 

Seems like a quick fix, I guess we can add `cast Oid.name` to decoder.

Would you mind opening a PR for that?

Also, just FYI, this lib is not really stable, nor anywhere near complete, so feel free to open issues/PRs if you find anything missing. I'm also very curious what you're building

**Comment by rokoucha** [comment]
@bartlomieju OK, I will open PR ASAP.
Would I fix test? Apparently there is no test to decoding strings.

**Comment by bartlomieju** [comment]
> @bartlomieju OK, I will open PR ASAP.
> Would I fix test? Apparently there is no test to decoding strings.

Well... better tests are still a TODO, so I'm ok with a PR without a test for now

**Comment by bartlomieju** [comment]
@rokoucha https://github.com/buildondata/deno-postgres/releases/tag/v0.3.5 happy coding!

**Comment by killbond007** [comment]
Hello @bartlomieju  , I have the same error when execute query. In my table users has column type  uuid.

**Comment by bartlomieju** [comment]
@killbond007 feel free to open a PR with new type
