### ISSUE TITLE
How about separating test_deps.ts from deps.ts

### ISSUE THREAD

**Issue by kt3k** [buildondata/deno-postgres#84]
How about separating test dependecies from runtime dependencies like [oak server does](https://github.com/oakserver/oak/blob/master/test_deps.ts)? That reduces the amount of the downloads for the users of this library.

**Comment by bartlomieju** [comment]
@kt3k yeah, great idea :+1:

**Comment by kt3k** [comment]
@bartlomieju Thank you for accepting the suggestion! I'll send a PR!
